name: infinity_sweeper
description: Infinity Sweeper.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.3.2+19

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.0
  easy_splash_screen: ^1.0.3
  flutter_svg: ^2.0.4
  flutter_neumorphic: ^3.2.0
  clay_containers: ^0.3.2
  flutter_launcher_icons: ^0.12.0
  shared_preferences: ^2.0.11
  fl_chart: ^0.61.0
  google_mobile_ads: ^2.3.0
  purchases_flutter: ^4.11.0
  games_services: ^3.0.1
  carousel_slider: ^4.0.0
  app_tracking_transparency: ^2.0.3
  material_design_icons_flutter: ^6.0.7096
  font_awesome_flutter: ^10.4.0
  icofont_flutter: ^1.4.0
  in_app_review: ^2.0.6
  flutter_email_sender: ^5.2.0
  country_flags: ^1.1.1
  
flutter_icons:
  ios: true
  android: true
  image_path: "assets/icons/icon.png"
  # optionally, as transparency is not allowed on app store
  remove_alpha_ios: true

dev_dependencies:
  test: ^1.22.0
  flutter_test:
    sdk: flutter
  change_app_package_name: any
  flutter_lints: ^2.0.1
  

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/icons_tutorial/
    - assets/icons_game_mode/
  fonts:
    - family: Futura Round
      fonts:
        - asset: assets/fonts/FuturaRound.ttf
        - asset: assets/fonts/FuturaRoundBold.ttf